orders_index:
    path:     /
    defaults: { _controller: "EcommerceAdminBundle:Orders:index" }
    methods:  GET

orders_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceAdminBundle:Orders:show" }
    methods:  GET

orders_new:
    path:     /new
    defaults: { _controller: "EcommerceAdminBundle:Orders:new" }
    methods:  [GET, POST]

orders_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceAdminBundle:Orders:edit" }
    methods:  [GET, POST]

orders_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceAdminBundle:Orders:delete" }
    methods:  DELETE
