ecommerce_user:
    resource: "@EcommerceUserBundle/Resources/config/routing.yml"
    prefix:   /

ecommerce_admin:
    resource: "@EcommerceAdminBundle/Resources/config/routing.yml"
    prefix:

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


admin_login:
    path:  /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }

admin_login_check:
    path:  /admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

admin_logout:
    path:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

